apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.serviceAccount.name }}"
  labels:
    helm.sh/chart: "{{ .Values.serviceAccount.labels.helm-chart }}"
    app.kubernetes.io/name: checkout
    app.kubernetes.io/instance: checkout
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: retail-store-sample
    app.kubernetes.io/managed-by: Helm