serviceAccount:
  name: ui
  labels:
    helmChart: ui-1.2.4

image:
  repository: the-store-ui
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: ui
  type: ClusterIP
  port: 80
  targetPort: http

configmap:
  name: ui
  RETAIL_UI_ENDPOINTS_CATALOG: http://catalog
  RETAIL_UI_ENDPOINTS_CARTS: http://carts
  RETAIL_UI_ENDPOINTS_CHECKOUT: http://checkout
  RETAIL_UI_ENDPOINTS_ORDERS: http://orders
