serviceAccount:
  name: ui
  labels:
    helm-chart: ui-1.2.4

service:
  name: ui
  type: ClusterIP
  port: 80
  targetPort: http

configmap:
  name: checkout
  RETAIL_UI_ENDPOINTS_CATALOG: http://catalog
  RETAIL_UI_ENDPOINTS_CARTS: http://carts
  RETAIL_UI_ENDPOINTS_CHECKOUT: http://checkout
  RETAIL_UI_ENDPOINTS_ORDERS: http://orders