serviceAccount:
  name: catalog
  labels:
    helmChart: catalog-1.2.4

image:
  repository: the-store-catalog
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: catalog
  type: ClusterIP
  port: 80
  targetPort: http

configmap:
  name: catalog
  RETAIL_CATALOG_PERSISTENCE_PROVIDER: in-memory

secret:
  name: catalog-db
  RETAIL_CATALOG_PERSISTENCE_USER: Y2F0YWxvZw==
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: VXFxMXhMUlVLc1lXdmI0bQ==
