serviceAccount:
  name: checkout
  labels:
    helm-chart: checkout-1.2.4

service:
  name: checkout
  type: ClusterIP
  port: 80
  targetPort: http

configmap:
  name: checkout
  RETAIL_CHECKOUT_PERSISTENCE_PROVIDER: in-memory