serviceAccount:
  name: checkout
  labels:
    helmChart: checkout-1.2.4

image:
  repository: the-store-checkout
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: checkout
  type: ClusterIP
  port: 80
  targetPort: http

configmap:
  name: checkout
  RETAIL_CHECKOUT_PERSISTENCE_PROVIDER: in-memory
