serviceAccount:
  name: carts
  labels:
    helmChart: carts-1.2.4

image:
  repository: the-store-cart
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: carts
  type: ClusterIP
  port: 80
  targetPort: http

configmap:
  name: carts
  RETAIL_CART_PERSISTENCE_PROVIDER: in-memory
