apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.configmap.name }}"
data:
  RETAIL_ORDERS_MESSAGING_PROVIDER: "{{ .Values.configmap.RETAIL_ORDERS_MESSAGING_PROVIDER }}"
  RETAIL_ORDERS_PERSISTENCE_PROVIDER: "{{ .Values.configmap.RETAIL_ORDERS_PERSISTENCE_PROVIDER }}"