apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
  labels:
    helm.sh/chart: orders-1.2.4
    app.kubernetes.io/name: orders
    app.kubernetes.io/instance: orders
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: retail-store-sample
    app.kubernetes.io/managed-by: Helm
spec:
  type: "{{ .Values.service.type }}"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: "{{ .Values.service.targetPort }}"
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: orders
    app.kubernetes.io/instance: orders
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: retail-store-sample