apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.serviceAccount.name }}"
  labels:
    helm.sh/chart: "{{ .Values.serviceAccount.labels.helmChart }}"
    app.kubernetes.io/name: carts
    app.kubernetes.io/instance: carts
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: retail-store-sample
    app.kubernetes.io/managed-by: Helm