apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.secret.name }}"
data:
  RETAIL_CATALOG_PERSISTENCE_USER: "{{ .Values.secret.RETAIL_CATALOG_PERSISTENCE_USER }}"
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: "{{ .Values.secret.RETAIL_CATALOG_PERSISTENCE_PASSWORD }}"