name: Authenticate VPN

on:
  workflow_call:
    secrets:
      OVPN_CONFIG:
        required: true
      OVPN_CLIENT_KEY:
        required: true
      OVPN_TLS_AUTH_KEY:
        required: true
    outputs:
      vpn_status:
        description: "VPN authentication result"
        value: ${{ jobs.authenticate-vpn.outputs.vpn_status }}

jobs:
  authenticate-vpn:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Create OVPN config file
        run: |
          echo "${{ secrets.OVPN_CONFIG }}" > client.ovpn

      - name: Connect to VPN
        uses: kota65535/github-openvpn-connect-action@v2
        with:
          config_file: client.ovpn
          client_key: ${{ secrets.OVPN_CLIENT_KEY }}
          tls_auth_key: ${{ secrets.OVPN_TLS_AUTH_KEY }}
      
      - name: Set status
        id: set_status
        if: always() # ensure this runs even if connect fails
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "result=OVPN_KUBECONFIG" >> "$GITHUB_OUTPUT"
          else
            echo "result=KUBECONFIG" >> "$GITHUB_OUTPUT"
          fi
