name: CI/CD Pipeline

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]

jobs:
  lint:
    name: Lint Code Base
    uses: ./.github/workflows/lint.yml

  deploy:
    name: Deploy Services
    needs: lint
    uses: ./.github/workflows/main.yml

  build-and-push:
    name: Build and Push Docker Images
    needs: [lint, build-and-push]
    uses: ./.github/workflows/docker.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
